// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketSupportApp.Models;

[Index("PriorityName", Name = "UQ__TicketPr__346EBED6D52E37B1", IsUnique = true)]
public partial class TicketPriority
{
    [Key]
    public int PriorityID { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string PriorityName { get; set; }

    [InverseProperty("Priority")]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}