// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketSystem.Models;

public partial class Ticket
{
    [Key]
    public int TicketID { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Subject { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string Description { get; set; }

    [Required]
    [StringLength(450)]
    public string CustomerID { get; set; }

    [StringLength(450)]
    public string AssignedAgentID { get; set; }

    public int StatusID { get; set; }

    public int PriorityID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Category { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ResolvedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SLA_DueDate { get; set; }

    [ForeignKey("AssignedAgentID")]
    [InverseProperty("TicketAssignedAgents")]
    public virtual AspNetUser AssignedAgent { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("TicketCustomers")]
    public virtual AspNetUser Customer { get; set; }

    [ForeignKey("PriorityID")]
    [InverseProperty("Tickets")]
    public virtual TicketPriority Priority { get; set; }

    [ForeignKey("StatusID")]
    [InverseProperty("Tickets")]
    public virtual TicketStatus Status { get; set; }

    [InverseProperty("Ticket")]
    public virtual ICollection<TicketComment> TicketComments { get; set; } = new List<TicketComment>();
}