// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketSystem.Models;

[Table("TicketStatus")]
[Index("StatusName", Name = "UQ__TicketSt__05E7698AEBE7E1B0", IsUnique = true)]
public partial class TicketStatus
{
    [Key]
    public int StatusID { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string StatusName { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}