// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketSystem.Models;

[Table("TicketCategory")]
public partial class TicketCategory
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string CategoryName { get; set; }

    [InverseProperty("CategoryNavigation")]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}